### ISSUE TITLE
Question about the training epochs

### ISSUE THREAD

**Issue by HaozheQi** [zerchen/AlignSDF#11]
Hello, thank you for your excellent work. I have a question about the train epochs.

You set the total training epoch as 1600 for the Obman dataset. I wonder if the model really needs so many epochs to converge to a satisfactory state. By any chance, have you tried to train with more minor epochs or check the validation error?

Thank you very much in advance and look forward to your reply :D
Best.

**Comment by zerchen** [comment]
Hi,

Thanks for your questions.
Yes, I have tried training the model for 1300 epochs, and the model performs slightly worse in quantitative numbers than training it for 1600 epochs. For ObMan, I think you need to train at least 1300 epochs since the joint hand/sdf training starts at the 1200th epoch ([here](https://github.com/zerchen/AlignSDF/blob/a944dd0cac847bb61dd80f058b8c71d90ed56831/train.py#L476)). However, I could have a try for a setting with fewer training epochs (e.g., end_epoch=750, start_additional_loss=600). I plan to launch the experiment today and return to you when I get the result.

Best,
Zerui

**Comment by HaozheQi** [comment]
Hi, 

Thank you for your fast reply. The setting you are trying is exactly what I mean, i.e., start the additional loss earlier to have a smaller training epoch number. Look forward to your training result :D

Best.

**Comment by zerchen** [comment]
Hi,

The results are shown below. The first row (1600_epochs) is copied from row (g) in Table (3) of the AlignSDF paper.
| alignsdf_obman_87k | hand_chamfer | obj_chamfer | hand_joint | obj_joint |
|:------------:|:------------:|:-----------:|:----------:|:---------:|
|  1600_epochs |     0.136    |     3.38    |    1.27    |    3.29   |
|  750_epochs  |     0.134    |     3.74    |    1.15    |    3.24   |

It looks like that a longer training could benefit the object reconstruction quality but does not help for the hand side. Happy to see such results as it could help accelerate experimental iterations.

Hope it helps.

Best,
Zerui

**Comment by HaozheQi** [comment]
Hi, Zerui,

Yes, the result is beneficial to me. Thank you so much!

Best.
