### ISSUE TITLE
Hi, when i try to run the code,  i meet some problems.

### ISSUE THREAD

**Issue by zhangxinkang** [zerchen/AlignSDF#5]
Hi, sorry to ask so many questions.
1: I try to run the code, but obj_corners_3d and  obj_rest_corners_3d are not available while your code have used them.  Can you tell me the meanning of them, thus i can use trimesh to get them from the mesh.
2: The loss of corners is not in the paper.
3: I don't know if the code is the final version, is it just a reference but not a available code?

best
xinkang

**Comment by zerchen** [comment]
Hi, thanks for your interests.

1: The meaning of 'obj_corners_3d' is the eight corners of the 3D boxes that tightly bound the object in the camera coordinate space. 'obj_rest_corners_3d' is the position of these eight corners when the object is in the rest pose (i.e., the translation and rotation are zero). These two stuff is not important, and you could simply igore them. For the object, I only predict the object translation relative to the hand wrist.
2. Yes, I also don't use corner losses since it didn't bring me better performance. You could simply ignore it and set this loss to zero.
3. This code is in the final version, but it also contains some features (including predicting object corners) that I used for testing. For some features presented in the code but not mentioned in the paper, you could directly ignore them since I previously did experiments on them but didn't bring me gains.

**Comment by zhangxinkang** [comment]
> 

Thank you for your reply in your busy schedule.
I want to ask one more question.
I find the final **gt_obj_center** is from the **obj_corners_3d** in function unpack_meta_params() in sdf_utils.py, is there any other way to get gt_obj_center(i use trimesh to compute the oriented box of .obj in mesh_obj, but the loss of center is not good)

best
xinkang

**Comment by zerchen** [comment]
Hi Xinkang

Yes, I think you simply get the 'gt_obj_center' directly from the official obman annotation. When you opened one pkl file in the 'meta' directory, you could find a key called 'affine_transform', which is a 4x4 matrix. I remember the matrix[:3, 3] is the object center position in the camera coordinate system. You need to have a double check.
Hope it helps. I will also have a try to make the code easier to use at the end of this  month.

Best,
Zerui

**Comment by zhangxinkang** [comment]
Hi Zerui
Thanks for your patient reply, I'm a beginner and appreciate your guidance. Your work is excellent, and I wish you better work and better articles in the future.

Best，
Xinkang

**Comment by zerchen** [comment]
You are welcome :)

**Comment by zerchen** [comment]
Hi,

I have put my preprocessed data at https://drive.google.com/drive/folders/1GoaA6vB6TwAAHmaobVo5GjRoCq2wT21R, which could help resolve your issue. 

Best,
Zerui

**Comment by zhangxinkang** [comment]
> Hi,
> 
> I have put my preprocessed data at https://drive.google.com/drive/folders/1GoaA6vB6TwAAHmaobVo5GjRoCq2wT21R, which could help resolve your issue.
> 
> Best, Zerui

Hi,
Thank you ,zerui. 
Thank you for your data, I will use it properly.
By the way, I'm not familiar with the dexYCB dataset. Can you share your code for processing the dexYCB dataset and generating mesh.
Thank you for your selfless sharing.

Best,
Xinkang

**Comment by zerchen** [comment]
Hi @zhangxinkang,

You could refer to #8 to have more tips about processing DexYCB dataset and generating meshes.

Best,
Zerui

**Comment by zhangxinkang** [comment]
> Hi @zhangxinkang,
> 
> You could refer to #8 to have more tips about processing DexYCB dataset and generating meshes.
> 
> Best, Zerui

Hi, zerui, I am sorry i have not noticed the closed issue,thanks for your guidance.
